# Generated by Django 4.0.3 on 2022-05-11 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=datetime.date, upload_to='media/thumbnails'),
            preserve_default=False,
        ),
    ]
