# Generated by Django 4.0.3 on 2022-05-11 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/thumbnails'),
            preserve_default=False,
        ),
    ]
